<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('transactions', function (Blueprint $table) {
            $table->id('transaction_id');
            $table->double('amount');
            $table->string('status');
            $table->enum('type', ['deposit', 'withdrawal']);
            $table->multiLineString('transactionPurpose');
            $table->longText('referenceId')->unique()->comment('Auto generated by company and need to be unique');
            $table->timestamp('completedAt')->nullable();
            $table->timestamps();
            $table->unsignedBigInteger('tradingAccountId');
            $table->unsignedBigInteger('bankAccountId');
            $table->unsignedBigInteger('rejectId')->nullable();
            $table->unsignedBigInteger('completedBy')->nullable();
            $table->foreign('tradingAccountId')->references('id')->on('reject_reasons')->onDelete('cascade');
            $table->foreign('bankAccountId')->references('id')->on('bank_accounts')->onDelete('cascade');
            $table->foreign('rejectId')->references('id')->on('reject_reasons')->onDelete('cascade');
            $table->foreign('completedBy')->references('id')->on('users')->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('transactions');
    }
};
